### ISSUE TITLE
Grey icon while loading in mobile

### ISSUE THREAD

**Issue by Ananthu46** [stevenosse/flutter_emoji_feedback#1]
The default icon not displaying
![IMG_20230309_071137](https://user-images.githubusercontent.com/63265428/223893595-e948d2a2-e49e-4e2b-929f-84bc58aefdca.jpg)

**Comment by stevenosse** [comment]
Hello
Thank you for filing this issue.

Please are there some logs associated with this crash ? Could you share them ?

Also what is your environment config ? (flutter version)

Thank you

**Comment by stevenosse** [comment]
Hello
Any update ?

**Comment by dvkvicky93** [comment]
Can't able to change the selected emoji colour it default to yellow..how to change selected emoji colour if Awesome I want to show green colour,Very good I want to show red colour,good I want to show another colour etc..

**Comment by stevenosse** [comment]
Hello
Since the packages uses svg files to display emoji, we would need to edit  the svg files in runtime, which i don't think is feasable using the flutter_svg package.

You can still use the presetBuilder to build a custom item.
Let me know if you have any other questions.
