### ISSUE TITLE
init with focus

### ISSUE THREAD

**Issue by QebehutCrow** [stevenosse/flutter_emoji_feedback#2]
hello,
could you implement something to load the emoji-bar already focused on one emoji please?
so if someone already picked emoji 3 before you can store the value somewhere and let the widget focus on emoji 3 while loading?

greeting

**Comment by stevenosse** [comment]
Hello
I've just published [an update](https://pub.dev/packages/flutter_emoji_feedback) with that feature ^^
Let me know if you encounter any other issue.
